path:
  train_path: ./dataset/train.csv
  dev_path: ./dataset/valid.csv
  test_path: ./dataset/test.csv
  predict_path: ./dataset/finance_data.csv
  # inference를 하는 경우 로드할 모델의 경로를 입력해주세요.
  load_model_path: 

model:
  model_name: klue/roberta-base

train:
  max_epoch: 10
  batch_size: 32
  learning_rate: 2e-5
  loss: focal # loss.py 맨 아래 config 되어 있는 값을 받아서 loss 함수를 가져옵니다.
  save_steps: 250
  # save_steps은 반드시 eval_steps의 배수여야 합니다!!!! """n * save_steps = eval_steps"""
  eval_steps: 250
  logging_steps: 2000
  dropout: 0.2
  
utils:
  seed: 42
  monitor: micro f1 score
  top_k: 3
  patience: 20